name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        ctest
